# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import spring_pb2 as spring__pb2


class SubscriberStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Subscribe = channel.unary_stream(
        '/spring.Subscriber/Subscribe',
        request_serializer=spring__pb2.Regex.SerializeToString,
        response_deserializer=spring__pb2.Matches.FromString,
        )


class SubscriberServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SubscriberServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=spring__pb2.Regex.FromString,
          response_serializer=spring__pb2.Matches.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spring.Subscriber', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
